### ISSUE TITLE
Reporting - not working in dotnet 6 testing zip version

### ISSUE THREAD

**Issue by MartinFijneman** [RHEAGROUP/COMET-IME-Community-Edition#1220]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-IME
- [ ] I have searched [open](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Reporting - not working in dotnet 6 testing zip version

possible to open a report, but compiling and viewing the resulting report not possible.

error message in reporting browser:

08:29:03 Operation is not supported on this platform.\n   at Microsoft.CSharp.CSharpCodeGenerator.FromFileBatch(CompilerParameters options, String[] fileNames)
   at Microsoft.CSharp.CSharpCodeGenerator.FromSourceBatch(CompilerParameters options, String[] sources)
   at Microsoft.CSharp.CSharpCodeGenerator.System.CodeDom.Compiler.ICodeCompiler.CompileAssemblyFromSourceBatch(CompilerParameters options, String[] sources)
   at System.CodeDom.Compiler.CodeDomProvider.CompileAssemblyFromSource(CompilerParameters options, String[] sources)
   at CDP4Reporting.ViewModels.ReportDesignerViewModel.CompileAssembly(String source) in C:\Users\joratowski\Git\COMET-IME-Community-Edition\CDP4Reporting\ViewModels\ReportDesignerViewModel.cs:line 1162\n
08:29:05 Build data source code first.
08:29:05 Compile data source code first.
08:29:33 Operation is not supported on this platform.\n   at Microsoft.CSharp.CSharpCodeGenerator.FromFileBatch(CompilerParameters options, String[] fileNames)
   at Microsoft.CSharp.CSharpCodeGenerator.FromSourceBatch(CompilerParameters options, String[] sources)
   at Microsoft.CSharp.CSharpCodeGenerator.System.CodeDom.Compiler.ICodeCompiler.CompileAssemblyFromSourceBatch(CompilerParameters options, String[] sources)
   at System.CodeDom.Compiler.CodeDomProvider.CompileAssemblyFromSource(CompilerParameters options, String[] sources)
   at CDP4Reporting.ViewModels.ReportDesignerViewModel.CompileAssembly(String source) in C:\Users\joratowski\Git\COMET-IME-Community-Edition\CDP4Reporting\ViewModels\ReportDesignerViewModel.cs:line 1162\n

### Logs

  - [ ] There are no logs regarding the issue
  - { ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- COMET version:
  - [x] COMET-IME: dotnet 6 testing zip file version 20221221 15:30
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4/COMET Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by lxatrhea** [comment]
The Report app is partially converted, but the code compiler should be updated. The UI-DSM version should be used here.
Will be done in issue #1117 
This issue will therefore be closed.
