### ISSUE TITLE
Domain File Store - error when creating domain file store

### ISSUE THREAD

**Issue by MartinFijneman** [RHEAGROUP/COMET-IME-Community-Edition#842]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-IME
- [ ] I have searched [open](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Domain File Store - error when creating domain file store
action performed as admin user
error message included below

### Steps to Reproduce

open domain file store and try to create Domain File Store

### Logs

Error message:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at CDP4Dal.Session.<>c__DisplayClass42_0.<QuerySelectedDomainOfExpertise>b__0(KeyValuePair`2 x)
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at CDP4Dal.Session.QuerySelectedDomainOfExpertise(Iteration iteration)
   at CDP4EngineeringModel.ViewModels.DomainFileStoreDialogViewModel.UpdateProperties()
   at CDP4Composition.Mvvm.DialogViewModelBase`1..ctor(T thingClone, IThingTransaction parentTransaction, ISession session, Boolean isRoot, ThingDialogKind dialogKind, IThingDialogNavigationService thingDialogNavigationService, Thing container, IEnumerable`1 chainOfContainers)
   at CDP4CommonView.DomainFileStoreDialogViewModel..ctor(DomainFileStore domainFileStore, IThingTransaction transaction, ISession session, Boolean isRoot, ThingDialogKind dialogKind, IThingDialogNavigationService thingDialogNavigationService, Thing container, IEnumerable`1 chainOfContainers)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at CDP4Composition.Navigation.ThingDialogNavigationService.Navigate(Thing thing, IThingTransaction transaction, ISession session, Boolean isRoot, ThingDialogKind dialogKind, IThingDialogNavigationService thingDialogNavigationService, Thing container, IEnumerable`1 chainOfContainers)

  - [ ] There are no logs regarding the issue
  - { ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- COMET version:
  - [x] COMET-IME: 8.1.0 RC2
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4/COMET Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by lxatrhea** [comment]
Fixed in final 8.1.0 release
